sudo: required
services:
  - docker

before_install:
  - docker build -t nfhbar/fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nfhbar/fib-test npm test -- --coverage

after_success:
  - docker build -t nfhbar/fib-calculator-client ./client
  - docker build -t nfhbar/fib-calculator-nginx ./nginx
  - docker build -t nfhbar/fib-calculator-server ./server
  - docker build -t nfhbar/fib-calculator-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nfhbar/fib-calculator-client
  - docker push nfhbar/fib-calculator-nginx
  - docker push nfhbar/fib-calculator-server
  - docker push nfhbar/fib-calculator-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: nf-prod-fib-calculator-t
  env: nf-prod-fib-calculator-t
  bucket_name: elasticbeanstalk-us-east-2-259280065187
  bucket_path: fib-calculator
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_ACCESS_SECRET
